pipeline {

    agent {
    kubernetes {
        yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:

  - name: maven
    image: maven:3.9.6-eclipse-temurin-17
    command: ["sh", "-c", "cat"]
    tty: true

  - name: trivy
    image: aquasec/trivy:latest
    command: ["sh", "-c", "cat"]
    tty: true

  - name: helm
    image: alpine/helm:3.14.0
    command: ["sh", "-c", "cat"]
    tty: true

  volumeMounts:
  - name: docker-config
  mountPath: /kaniko/.docker
'''
    }
}

    environment {
        IMAGE_NAME = "panni1986/demo-app:latest"
    }

    stages {

        stage('Build') {
            steps {
                container('maven') {
                    dir('app') {
                    sh 'mvn clean package'
                    }
                }
            }
        }

        stage('SonarQube') {
            steps {
                container('maven') {
                    dir('app') {
                    sh '''
                    mvn sonar:sonar \
                    -Dsonar.host.url=http://sonarqube:9000 \
                    -Dsonar.login=$SONAR_AUTH_TOKEN
                    '''
                   }
                }
            }
        }

        stage('Trivy FS Scan') {
            steps {
                container('trivy') {
                    sh 'trivy fs .'
                }
            }
        }

        stage('Kaniko Build & Push') {
           steps {
             sh '''
            /kaniko/executor \
             --dockerfile=app/Dockerfile \
             --context=dir://app \
             --destination=panni1986/demo-app:latest \
             --skip-tls-verify
            '''
           }
        }
        
        stage('Trivy Image Scan') {
            steps {
                container('trivy') {
                    sh 'trivy image $IMAGE_NAME'
                }
            }
        }

        stage('Deploy Helm') {
            steps {
                container('helm') {
                    sh 'helm upgrade --install demo helm/demo-app'
                }
            }
        }
    }
}